#!/bin/bash
#
## 	binadit firewall installation script.
## 	This script must be run as root and be executable (chmod +x /etc/init.d/firewall)
##
## 	Just added IPv6 | june 2013
## 	DMZ IPv6 | sept 2013
## 	Blacklist ipv6 | nov 2013
## 	Added ips for SSH Access | feb 2014
## 	IP range dmz in- and output | mrt 2014
## 	IP range dmz fix voor IPv6 | may 2014
## 	ICMP types activated voor IPv4  | nov 2014
## 	Added multicast enable option | nov 2014
##  Added SSH port detection
##
## TODO
##
## Some sort of DDOS attack prevention
## -A INPUT -p tcp --dport 80 -m limit --limit 25/minute --limit-burst 100 -j ACCEPT
#
#chkconfig: 345 99 01

SERVICE=`which service`
iptablesFile="/etc/sysconfig/iptables"
ip6tablesFile="/etc/sysconfig/ip6tables"
SSHPORT=`grep "Port " /etc/ssh/sshd_config | awk '{print $2}'`

if [ -f /etc/debian_version ]; then
	iptablesFile="/etc/iptables/rules.v4"
	ip6tablesFile="/etc/iptables/rules.v6"
fi

source /etc/firewall.d/host.conf

purge() {
  echo -n "Firewall: Purging and allowing all traffic"
  $SERVICE iptables stop
  $SERVICE ip6tables stop
  echo
}

setup() {
  $SERVICE iptables stop  
  touch $iptablesFile
  echo "# Firewall configuration written by /etc/init.d/firewall
# To Add ports or IP addresses, edit /etc/firewall.d/host.conf
#
# Firewall written by Ronald Jonkers - binadit NL 2013
#
*filter
:INPUT DROP [0:0]
:FORWARD DROP [6:425]
:OUTPUT DROP [234:310548]
:LOGGING - [0:0]
#LOCALHOST
-A INPUT -i lo -j ACCEPT
-A OUTPUT -o lo -j ACCEPT" > $iptablesFile

  echo "-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT  
# Open DNS ports
-A OUTPUT -p udp --dport 53 -j ACCEPT
-A INPUT -p udp --dport 53 -j ACCEPT
-A OUTPUT -p tcp --dport 53 -j ACCEPT
-A INPUT -p tcp --dport 53 -j ACCEPT" >> $iptablesFile
  for port in $TCPPORTS ; do
    echo "-A INPUT -p tcp --dport $port -j ACCEPT
-A OUTPUT -p tcp --dport $port -j ACCEPT" >> $iptablesFile
  done
  
  for port in $TCPPORTS_INPUT ; do
    echo "-A INPUT -p tcp --dport $port -j ACCEPT" >> $iptablesFile
  done
  for port in $TCPPORTS_OUTPUT ; do
    echo "-A OUTPUT -p tcp --dport $port -j ACCEPT" >> $iptablesFile
  done
  
  for ip in $SSHACCESS; do
    echo "-A INPUT -p tcp --dport $SSHPORT -s $ip -j ACCEPT
-A OUTPUT -p tcp --dport $SSHPORT -s $ip -j ACCEPT" >> $iptablesFile
  done
  echo "# Open UDP ports" >> $iptablesFile
  for port in $UDPPORTS ; do
    echo "-A INPUT -p udp --dport $port -j ACCEPT
-A OUTPUT -p udp --dport $port -j ACCEPT" >> $iptablesFile
  done
  echo "# Open IP addresses" >> $iptablesFile
  for ip in $DMZS ; do
    echo "-A INPUT -s $ip -j ACCEPT
-A OUTPUT -d $ip -j ACCEPT" >> $iptablesFile
  done
  for ip in $DMZRANGE ; do
    echo "-A INPUT -m iprange --src-range $ip -j ACCEPT
-A OUTPUT -m iprange --dst-range $ip -j ACCEPT" >> $iptablesFile
  done
  echo "# Blocked IP addresses" >> $iptablesFile
  for ip in $BLACKLIST ; do
    echo "-A INPUT -s $ip -j DROP
-A OUTPUT -s $ip -j DROP" >> $iptablesFile
  done
  echo "# Blocked IP ranges" >> $iptablesFile
  for ip in $BLOCKRANGE ; do
    echo "-A INPUT -m iprange --src-range $ip -j DROP
-A OUTPUT -m iprange --src-range $ip -j DROP" >> $iptablesFile
  done

if [ "$MULTICAST_ENABLE" == "TRUE" ]; then
  echo "# Multicast
#-A INPUT -d 224.0.0.0/8 -j ACCEPT
#-A OUTPUT -d 224.0.0.0/8 -j ACCEPT
#-I INPUT -p udp -m state --state NEW -m multiport --dports 5404,5405 -j ACCEPT 
#-I OUTPUT -p udp -m state --state NEW -m multiport --dports 5404,5405 -j ACCEPT 
-A INPUT -m pkttype --pkt-type multicast -j ACCEPT
-A INPUT -m pkttype --pkt-type broadcast -j ACCEPT
-A OUTPUT -m pkttype --pkt-type multicast -j ACCEPT
-A OUTPUT -m pkttype --pkt-type broadcast -j ACCEPT" >> $iptablesFile
fi

echo "# SPAM security" >> $iptablesFile
echo "-A OUTPUT -d 127.0.0.1 -p tcp -m tcp --dport 25 -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 25 -m limit --limit 10/sec -m owner --gid-owner mail -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 25 -m limit --limit 10/sec -m owner --gid-owner postfix -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 25 -m limit --limit 10/sec -m owner --uid-owner root -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 25 -j REJECT --reject-with icmp-port-unreachable" >> $iptablesFile

  echo '# Enable ICMP
-A INPUT -p icmp -m icmp --icmp-type host-unreachable -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type port-unreachable -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type fragmentation-needed -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type source-quench -j ACCEPT
#-A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
#-A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A OUTPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A OUTPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT

# LOGGING
-A INPUT -j LOGGING
-A LOGGING -m limit --limit 2/min -j LOG --log-prefix "IPTables Packet Dropped: " --log-level 7
-A LOGGING -j DROP
'  >> $iptablesFile
  
  echo "COMMIT" >> $iptablesFile
  
  $SERVICE iptables start
  
# IPv6 FIREWALL
  $SERVICE ip6tables stop
  /bin/touch $ip6tablesFile
  echo "# Firewall configuration written by /etc/init.d/firewall.sh
# To Add ports or IP addresses, edit /etc/firewall.d/host.conf
#
# Firewall written by Ronald Jonkers - binadit NL 2013
#
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT DROP [0:0]
#LOCALHOST
-A INPUT -i lo -j ACCEPT
-A OUTPUT -o lo -j ACCEPT" > $ip6tablesFile

  echo "# Open TCP ports
-A INPUT -m state --state ESTABLISHED -j ACCEPT
-A OUTPUT -m state --state ESTABLISHED -j ACCEPT" >> $ip6tablesFile
  for port in $TCPPORTS ; do
    echo "-A INPUT -p tcp --dport $port -j ACCEPT
-A OUTPUT -p tcp --dport $port -j ACCEPT" >> $ip6tablesFile
  done
  
  echo "# Open TCP incomming ports" >> $ip6tablesFile
  for port in $TCPPORTS_INPUT ; do
    echo "-A INPUT -p tcp --dport $port -j ACCEPT" >> $ip6tablesFile
  done
  echo "# Open TCP outgoing ports" >> $ip6tablesFile
  for port in $TCPPORTS_OUTPUT ; do
    echo "-A OUTPUT -p tcp --dport $port -j ACCEPT" >> $ip6tablesFile
  done
  
  
  echo "# Open UDP ports" >> $ip6tablesFile
  for port in $UDPPORTS ; do
    echo "-A INPUT -p udp --dport $port -j ACCEPT
-A OUTPUT -p udp --dport $port -j ACCEPT" >> $ip6tablesFile
  done
  echo "# Open IP addresses" >> $ip6tablesFile
  for ip in $DMZS_IPv6 ; do
    echo "-A INPUT -m iprange --src-range $ip -j ACCEPT
-A OUTPUT -m iprange --dst-range $ip -j ACCEPT" >> $ip6tablesFile
  done
  echo "# Blocked IP addresses" >> $ip6tablesFile
  for ip in $BLACKLIST_IPv6 ; do
    echo "-A INPUT -s $ip -j DROP" >> $ip6tablesFile
  done

  if [ "$MULTICAST_ENABLE" == "TRUE" ]; then
  echo "# Multicast
#-I INPUT -p udp -m state --state NEW -m multiport --dports 5404,5405 -j ACCEPT 
#-I OUTPUT -p udp -m state --state NEW -m multiport --dports 5404,5405 -j ACCEPT 
-A INPUT -m pkttype --pkt-type multicast -j ACCEPT
-A INPUT -m pkttype --pkt-type broadcast -j ACCEPT
-A OUTPUT -m pkttype --pkt-type multicast -j ACCEPT
-A OUTPUT -m pkttype --pkt-type broadcast -j ACCEPT" >> $iptablesFile
fi
  
  echo "# SPAM security" >> $ip6tablesFile
  echo "-A OUTPUT -d ::1 -p tcp -m tcp --dport 25 -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 25 -m owner --gid-owner mail -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 25 -m owner --gid-owner postfix -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 25 -m owner --uid-owner root -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 25 -j REJECT --reject-with icmp6-adm-prohibited" >> $ip6tablesFile
  
  echo "COMMIT" >> $ip6tablesFile
  
  $SERVICE ip6tables start
  
  
}

case "$1" in
  start)
    echo "Starting firewall..."
    purge
    setup
    ;;
  stop)
    echo "Stopping firewall..."
    purge
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    iptables -n -L
    ip6tables -n -L
    ;;
  *)
    echo "Usage: $0 <start|stop|restart|status>"
    ;;
esac